---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: proxyheaders
  namespace: development
spec:
  headers:
    sslProxyHeaders:
      X-Forwarded-Proto: "https"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-internal
  namespace: development
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jenkins.local`)
      kind: Rule
      services:
        - kind: Service
          name: jenkins
          namespace: development
          port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: development
spec:
  entryPoints:
    - websecure
  middlewares:
    - proxyheaders
  routes:
    - match: Host(`jenkins.my.domain`)
      kind: Rule
      services:
        - kind: Service
          name: jenkins
          namespace: development
          port: 8080
