apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: httpbin
    hosts:
    - jenkins.cornerstones.space
  rules:
  - host: jenkins.cornerstones.space
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
