apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-jenkins
  namespace: development
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.10.10
    path: "/jenkins"
