apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-jenkins
  namespace: development
spec:
  volumeName: nfs-pv-jenkins
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
