jenkins:
  controller:
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - configuration-as-code
    additionalPlugins:
      - ansicolor
      - antisamy-markup-formatter
      - blueocean
      - build-timeout
      - configuration-as-code-groovy
      - configuration-as-code-secret-ssm
      - dashboard-view
      - datadog
      - dependency-check-jenkins-plugin
      - ec2-fleet
      - email-ext
      - envinject
      - exclusive-execution
      - extra-columns
      - generic-webhook-trigger
      - greenballs
      - groovy
      - job-dsl
      - junit
      - lockable-resources
      - mailer
      - matrix-auth
      - maven-plugin
      - metrics
      - metrics-datadog
      - monitoring
      - naginator
      - pagerduty
      - parameterized-trigger
      - pipeline-aws
      - pipeline-stage-view
      - pipeline-utility-steps
      - PrioritySorter
      - rebuild
      - resource-disposer
      - run-condition
      - saml
      - slack
      - test-results-analyzer
      - throttle-concurrents
      - timestamper
      - ws-cleanup
    serviceType: LoadBalancer
    JCasC:
      defaultConfig: true

    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "8192Mi"
    javaOpts: "-Xms512m -Xmx8192m"

  agent:
    enabled: true
    resources:
      requests:
        memory: "1024Mi"
      limits:
        memory: "1024Mi"
  persistence:
    enabled: true
    size: 20Gi
